# Trigger deployment only on push to main branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to S3
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout the files
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.17.1'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Delete everything in the S3 bucket
        run: |
          aws s3 rm s3://sdp-smart-cities --recursive

      - name: Sync 'out' folder with S3 bucket
        run: |
          aws s3 sync out/ s3://sdp-smart-cities
